// generated by nd gen routes, do not modify

import type { Hash } from './types';

export enum WebRoutes {
  App = '/',
  Docs = '/docs',
  DocsApi = '/docs/api',
  DocsErrors = '/docs/errors',
  DocsLink = '/docs/ngrok-link',
  Download = '/download',
  Pricing = '/pricing',
  Privacy = '/privacy',
  ProductLink = '/product/ngrok-link',
  Solutions = 'https://solutions.ngrok.com/vpn-alternative',
  Tos = '/tos',
  DocsErrorsShow = '/docs/errors/:id',
}

export type DocsErrorsShowParams = {
  id?: string;
};

export const makeDocsErrorsShowPath = (id: string | undefined) =>
  `/docs/errors/${id ?? ''}`;

export const getWebUrl = (hostname: string, route: WebRoutes, hash?: Hash) =>
  route.startsWith('/') ? `${hostname}${route}${hash}` : `${route}${hash}`;
